export const changelogData: any = {
  "1.3": [
    "-Added a true Picture-In-Picture mode (not limited to Facebook only)",
    "-Minor fixes and improvements"
  ],
  "1.2": [
    "-Reworked & improved settings menu UI",
    "-Removed the popup menu (clicking on the icon will now open settings)",
    "-Extension is now enabled by default",
    "-Emote menu is also enabled by default",
    "-Performance optimizations, minor fixes and other improvements",
  ],
  "1.1": [
    "-Rewrote some parts of the extension",
    "-Fixed emotes (now load instantly)",
    "-Fixed highlighting keywords",
    "-Performance optimizations",
    "-Other minor fixes, improvements",
  ],
  "1.0.0": [
    "-Official website! dopechat.ddns.net - Extension overview, a look at features, changelog, dashboard.",
    "--Dashboard",
    "--Current dashboard features:",
    "---Streamers now can create their own emote set (RatedEpicz, Ramee, Vader sets are already in)",
    "---Login with Twitch and upload your own emotes",
    "---View all current emotes in the extension",
    "---Emote set mods can view/edit emote sets easily, and it will automatically update on the extension",
    "---Support the extension",
    "---View streamer&apos;s full emote set by going dopechat.ddns.net/dashboard/set/[streamer name]",
    "---Contact form to report bugs/issues and submit ideas",
    "---View all current emotes in the extension",
    "-Rewrote like 80% of the extension&apos;s code",
    "-Reworked a big part of the extension:",
    "--No more installing emote sets: ",
    "---Global emotes:",
    "----Global emotes available in every streamer&apos;s channel, handpicked by extension mods. Will be constantly updated with new emotes.",
    "---Channel emotes:",
    "----If the streamer has an emote set made in the new website, mods will approve it and it will automatically be enabled on the channel ready to use.",
    "-Improved settings UI:",
    "--Font settings now show 50+ font options, with the ability to add your own fonts",
    "--Random username colors toggle (enabled by default)",
    " --Made it easier to add new highlighted keywords, with a 'Remove all' button",
    "-Updated emote menu:",
    "--Reworked emote menu completely",
    "--You can either click on the emote menu button or ALT+E to bring up the emote menu (it's no longer draggable)",
    "--Emote menu search:",
    "---TAB to autocomplete the emote name",
    "---TAB also inputs the first emote into the chatbox (if you have typed anything in it)",
    "--Left navigation:",
    "---Buttons for global/streamer emotes and extension settings",
    "-TAB autocomplete emotes:",
    "--You can now press TAB while typing in the chat input box to autocomplete emotes.",
    "--Type exact start of emote codes, ex. Pepe finds all the emotes starting with 'Pepe&quot', 'PepeL' or 'Pepeg' narrows downthe search and so on.",
    "--Theatre mode no longer has a button, use the keyboard shortcut ALT+T (button clutter)",
    "-Moved 'Enable emote set' to the Other settings tab",
    "-Fixed emote menu sometimes causing browsers to lag (now loads 'infinitely' emotes - scroll down to load more)",
    "-Other minor fixes and improvements",
    "-Timestamps in chat toggle (in settings, hidden by default)",
  ],
  "0.3.5": ["Minor fixes, improvements."],
  "0.3.4": [
    "improved settings page with a better logo and top bar",
    "about page:",
    "-export chat appearance settings",
    "-import chat appearance settings",
    "-moved reset to default settings to about page",
    "minor improvements",
  ],
  "0.3.3": [
    "theatre mode (next to popout chat button or ALT+T keyboard shortcut)",
    "performance improvements:",
    "-chat appearance doesn&apos;t check for new values every second anymore, so it won&apos;t update live, but either after something has changed in the page like a new message typed in chat, or you refresh the page",
    "-random username coloring doesn&apos;t check every half a second anymore, it now detects if there&apos;s a new message in chat and updates instantly",
  ],
  "0.3.2": [
    "double click to open emote menu, so that it doesn&apos;t open while dragging",
    "chat appearance presets",
    "fixed chat popout button not showing up when switching pages",
    "added version in popup menu instead of 'welcome to fb gaming' update pages so you could follow updates",
    "minor improvements, fixes",
  ],
  "0.3.1": [
    "you can now install multiple emote sets (and uninstall)",
    "emote count while viewing emotes",
  ],
  "0.3.0": [
    "overhauled settings &amp; popup menu:",
    " -interactive chat appearance changing, no more toggles",
    "-overhauled viewing emotes in settings",
    "-installed emote set visible in the popup menu",
    "-added faq and tutorials in extension's settings (not finished)",
    "-advanced emote set dashboard (for mods)",
    "sets are updated automatically without the need to update the extension or import a new set",
    "popout chat",
    "added tooltips for emotes in the emote menu",
    "minor improvements",
  ],
  "0.2.7": [
    "feedback for reset to defaults",
    "hide replies toggle",
    "fixed chat split/message separator setting",
    "notification when the extension is updated",
    "fixed random color usernames",
    "mac support",
    "fixed firefox version",
    "minor improvements",
  ],
  "0.2.6.4": [
    "removed annoying emotes from the bottom of the live stream",
    "fixed wide emotes",
    "readability setting: separate chat messages",
    "tooltips for settings",
    "vod chat background",
    "reset to defaults button in settings",
    "tooltips for settings",
    "extension now only works in livestream and vods pages",
  ],
  "0.2.6": [
    "emote menu",
    "like/reply buttons toggle",
    "fixed chat messages alignment with usernames",
    "custom color for names in chat",
    "fixed random color usernames in compact mode / dark mode / light mode",
    "remove chat top bar toggle",
    "tooltips for emotes",
    "chat width doesn't require to type px anymore",
    "remove comment reactions toggle",
    "remove three dots toggle",
    "minor improvements",
  ],
  "0.1.0": ["initial release"],
};
